### ISSUE TITLE
urllib3 error

### ISSUE THREAD

**Issue by Grazulex** [guirem/plugin-googlecast#100]
## Description
/usr/local/lib/python3.7/dist-packages/requests/__init__.py:114: RequestsDependencyWarning: urllib3 (2.0.1) or chardet (5.1.0)/charset_normalizer (3.1.0) doesn't match a supported version!
RequestsDependencyWarning,
Traceback (most recent call last):
File "/var/www/html/plugins/googlecast/resources/googlecast.py", line 45, in 
import pychromecast.pychromecast as pychromecast
File "/var/www/html/plugins/googlecast/resources/pychromecast/pychromecast/__init__.py", line 12, in 
from . import socket_client
File "/var/www/html/plugins/googlecast/resources/pychromecast/pychromecast/socket_client.py", line 23, in 
from . import cast_channel_pb2
File "/var/www/html/plugins/googlecast/resources/pychromecast/pychromecast/cast_channel_pb2.py", line 36, in 
type=None),
File "/usr/local/lib/python3.7/dist-packages/google/protobuf/descriptor.py", line 796, in __new__
_message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
1. Downgrade the protobuf package to 3.20.x or lower.
2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

## Etapes à reproduire (pour les bugs)
je suis sur une image Jeedom a jour : 
Version : 4.3.17
Source : default
Branche : V4-stable
Système : diy

Tous les élements sont à jours

j'ai restarter mon serveur Jeedom et je ne sais plus démarrer les demon de Google Cast du à cette erreur.
Que dois-je faire ?

Merci

**Comment by Grazulex** [comment]
Pour info, j'ai fais le downgrade et cela fonctionne.
