### ISSUE TITLE
Traceback python

### ISSUE THREAD

**Issue by spyjo** [guirem/plugin-googlecast#42]
## Description

Hier j'ai installé le plugin, paramétré avec Google Home, tout a très bien fonctionné, le TTS était bien OK.
Ce matin, je me dis que je vais ajouter une clé api google speech histoire de tester la différence avec le tts google translate par défaut.
Mais suite à la sauvegarde des paramètres, le daemon ne veut plus redémarrer et part toujours en erreur:

```
Traceback (most recent call last):
File "/var/www/jeedom/plugins/googlecast/resources/googlecast.py", line 35, in <module>
from pydub import AudioSegment
File "/var/www/jeedom/plugins/googlecast/resources/pydub/__init__.py", line 1, in <module>
from .audio_segment import AudioSegment
File "/var/www/jeedom/plugins/googlecast/resources/pydub/audio_segment.py", line 148, in <module>
class AudioSegment(object):
File "/var/www/jeedom/plugins/googlecast/resources/pydub/audio_segment.py", line 159, in AudioSegment
converter = get_encoder_name()  # either ffmpeg or avconv
File "/var/www/jeedom/plugins/googlecast/resources/pydub/utils.py", line 168, in get_encoder_name
if which("avconv"):
File "/var/www/jeedom/plugins/googlecast/resources/pydub/utils.py", line 156, in which
envdir_list = [os.curdir] + os.environ["PATH"].split(os.pathsep)
File "/usr/lib/python3.5/os.py", line 725, in __getitem__
raise KeyError(key) from None
KeyError: 'PATH'
```

Même si je reviens au paramètres d'origine, le deamon ne repart jamais.

## Environnement:

* **Version Jeedom**: 3.2.12
* **Plateforme**: Debian Stretch
* **Version du Plugin**: 2018-12-11 23:30:56

**Comment by spyjo** [comment]
J'ai fait une modif vite fait dans googlecast.py pour corriger mon soucis: 

juste après :
import os,re
import os.path

j'ai ajouté :
os.environ.setdefault('PATH', '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin')

ça remarche de nouveau.. je ne comprend pas comment ça a pu marcher hier et plus ajourd'hui.
