### ISSUE TITLE
Problème de TTS (lié à l'installation des dépendances)

### ISSUE THREAD

**Issue by Adrimau** [guirem/plugin-googlecast#49]
## Contexte : j'ai fait une clean install de Jeedom v4 et le TTS ne fonctionne pas.

Log googlecast_local :
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/31062488/67091242-6e608900-f1ac-11e9-9758-9288de7fda5f.png">

La partie de googlecast_update qui pose problème :
<img width="745" alt="image" src="https://user-images.githubusercontent.com/31062488/67091299-9354fc00-f1ac-11e9-9339-65888dce0e2e.png">

J'ai essayé les différentes choses proposées à la fin de la doc en cas de problème de TTS mais sans succès.

Merci d'avance.

**Comment by guirem** [comment]
Bonjour,

Est-il possible d'avoir les logs en mode debug?
Le répertoire /var/www/html/plugins/googlecast/tmp existe-t-il?

**Comment by Adrimau** [comment]
Oui le répertoire existe, j'ai un fichier a2121caca59612b69f0929c2c18e99b4.mp3 dedans, c'est tout.

Voici les logs en mode DEBUG :

Googlecast_update : https://paste.ofcode.org/3RC2sTcmkLKfEcmC58GraG
Googlecast_local (après avoir lancé la commande "Parle !") : https://paste.ofcode.org/Q4Qu5jR7yiteRBEgszeuVp

**Comment by guirem** [comment]
C'est sur quel OS et hardware?
Peux tu essayer `sudo apt-get install -y sox` ?

**Comment by Adrimau** [comment]
Raspbian Buster Lite (installation très récente donc j'imagine la dernière version) sur RPi 3B.

Après avoir lancé ta ligne, aucune différence dans Googlecast_update, et voici le nouveau Googlecast_local : https://paste.ofcode.org/rUUjf4Ai64VEk46zAy83pq

**Comment by guirem** [comment]
Essaie avec
sudo apt-get install -y ffmpeg

**Comment by Adrimau** [comment]
C'est fait, aucun changement côté log

**Comment by Adrimau** [comment]
Alors, j'ai un peu avancé. J'ai DL puis installé (dans cet ordre) libttspico-data, libttspico0_1.0 et enfin libttspico-utils, et je n'ai plus l'erreur lié à ces paquets (lors de l'installation des dépendances).

J'ai aussi une erreur qui a disparue quand je lance un "Parle !", je n'ai plus que la ligne par rapport à l'API Google Translate. Et pour cause, même si j'ai celle-ci de sélectionnée dans la config du plugin, j'ai la voix du PicoTTS.

J'aurais bien installé  libav-tools manuellement aussi mais pour le coup lui n'est vraiment plus compatible Buster, on me dit d'installer ffppeg, ce qui est déjà le cas.

**Comment by Adrimau** [comment]
Si jamais ça peut aider, voici ce qui se passe plus précisément avant de passer en PicoTTS :

`[2019-10-19 10:43:30][DEBUG] : CMD-TTS------Generating file
[2019-10-19 10:43:30][DEBUG] : SENDER------Send to jeedom : {'devices': {'d3b4fb52-e3ac-71f6-1f53-b212bea83abb': {'uuid': 'd3b4fb52-e3ac-71f6-1f53-b212bea83abb', 'status': {'uuid': 'd3b4fb52-e3ac-71f6-1f53-b212bea83abb', 'uri': '192.168.0.85:8009', 'friendly_name': 'Hub', 'is_active_input': False, 'is_stand_by': True, 'volume_level': 81, 'volume_muted': False, 'app_id': 'E8C28D3C', 'display_name': 'Backdrop', 'status_text': '&nbsp;', 'is_busy': False, 'title': '', 'artist': '', 'series_title': '', 'stream_type': 'UNKNOWN', 'player_state': 'UNKNOWN'}, 'typemsg': 'info', 'lastOnline': 1571478196, 'online': True, 'lastSent': 1571478210, 'lastOfflineSent': 0, 'options': {'ignore_CEC': '0'}, 'lastScan': 1571478202}}}
sox FAIL formats: no handler for file extension `mp3'
[2019-10-19 10:43:31][ERROR] : CMD-TTS------Google Translate API : Cannot connect to API - failover to picotts  ([Errno 2] No such file or directory: '/var/www/html/plugins/googlecast/tmp/95c365bec826a5c4e31298200ed4c188.mp3')
[2019-10-19 10:43:31][DEBUG] : Traceback (most recent call last):
File "/var/www/html/plugins/googlecast/resources/googlecast.py", line 1435, in get_tts_data
speech = AudioSegment.from_mp3(filenamemp3)
File "/var/www/html/plugins/googlecast/resources/pydub/audio_segment.py", line 702, in from_mp3
return cls.from_file(file, 'mp3', parameters)
File "/var/www/html/plugins/googlecast/resources/pydub/audio_segment.py", line 603, in from_file
file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)
File "/var/www/html/plugins/googlecast/resources/pydub/utils.py", line 60, in _fd_or_path_or_tempfile
fd = open(fd, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/html/plugins/googlecast/tmp/95c365bec826a5c4e31298200ed4c188.mp3'`

**Comment by guirem** [comment]
Tu as bien accès a internet depuis ton raspberry?
`ping translate.google.com` donne bien quelque chose ?
As tu tenté avec tts 'Google Speach API'?

**Comment by Adrimau** [comment]
Oui bien sûr, le ping fonctionne. Non je n'ai pas tenté, mais je n'ai pas envie d'avoir à utiliser une clé API
