### ISSUE TITLE
Démon statut NOK

### ISSUE THREAD

**Issue by Licoti** [guirem/plugin-googlecast#75]
Bonjour,
J'ai un souci avec le lancement du démon.
Depuis la doc, j'ai vu cette commande dans la partie "Les dépendances sont 'ok' mais le démon ne se lance pas"
sudo pip3 uninstall -y requests zeroconf click bs4 six tqdm websocket-client

J'ai aussi testé ces commandes car j'avais le même problème que la personne sur ce forum : https://community.jeedom.com/t/probleme-demon-nok-googlecast/13449/17
sudo pip3 uninstall -y bs4 beautifulsoup4
sudo pip3 install 'beautifulsoup4>=4.8.0'
Depuis mes logs ont changés et je ne sais plus quoi faire.
Merci beaucoup pour votre aide.

* **Version Jeedom**: V 4.0.61
* **Plateforme**: raspberry pi 3 (jessie)
* **Version du Plugin**: 2020-07-04 13:20:21

**Voici les logs googlecast_local :**
ERROR:root:ERROR: Main pychromecast module not loaded !
ERROR:root:Traceback (most recent call last):
File "/var/www/html/plugins/googlecast/resources/googlecast.py", line 45, in <module>
import pychromecast.pychromecast as pychromecast
File "/var/www/html/plugins/googlecast/resources/pychromecast/pychromecast/__init__.py", line 12, in <module>
from . import socket_client
File "/var/www/html/plugins/googlecast/resources/pychromecast/pychromecast/socket_client.py", line 23, in <module>
from . import cast_channel_pb2
File "/var/www/html/plugins/googlecast/resources/pychromecast/pychromecast/cast_channel_pb2.py", line 6, in <module>
from google.protobuf.internal import enum_type_wrapper
ImportError: No module named 'google'

**logs googlecast_update :**
Launch install of googlecast dependancies
-- Current OS version :
Description:	Raspbian GNU/Linux 8.0 (jessie)
-- Updating repo...
Hit http://mirrordirector.raspbian.org jessie InRelease
Hit http://archive.raspberrypi.org jessie InRelease
Hit http://mirrordirector.raspbian.org jessie/main armhf Packages
Hit http://archive.raspberrypi.org jessie/main armhf Packages
Hit http://mirrordirector.raspbian.org jessie/contrib armhf Packages
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Hit http://mirrordirector.raspbian.org jessie/non-free armhf Packages
Hit http://mirrordirector.raspbian.org jessie/rpi armhf Packages
Hit https://deb.nodesource.com jessie InRelease
Ign http://archive.raspberrypi.org jessie/main Translation-en
Hit https://deb.nodesource.com jessie/main Sources
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Hit https://deb.nodesource.com jessie/main armhf Packages
Get:1 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:2 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:3 https://deb.nodesource.com jessie/main Translation-en [162 B]
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Get:4 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:5 https://deb.nodesource.com jessie/main Translation-en [162 B]
Ign https://deb.nodesource.com jessie/main Translation-en
Reading package lists...
-- Installation of python3 and dependancies
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version.
python-dev is already the newest version.
python3 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
-- Installed version of Python :
Python 3.5.2
Your version of python is compatible with this plugin.
-- Installation of pip for python3 and necessary libraries
Reading package lists...
Building dependency tree...
Reading state information...
python-requests is already the newest version.
python3-dev is already the newest version.
python3-pip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
-- Installation of audio sox library
Reading package lists...
Building dependency tree...
Reading state information...
sox is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
-- Installation of TTS libraries
Reading package lists...
Building dependency tree...
Reading state information...
libttspico-utils is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
-- Installation of libav/ffmpeg libraries
Reading package lists...
Building dependency tree...
Reading state information...
libav-tools is already the newest version.
libavcodec-extra is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
-- Upgrade setuptools with command pip3.5 if not up to date
WARNING: You are using pip version 20.1; however, version 20.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Requirement already satisfied: setuptools>=42.0.0 in /usr/local/lib/python3.5/site-packages (46.1.3)
-- Installed version of pip :
pip 20.1 from /usr/local/lib/python3.5/site-packages/pip (python 3.5)
-- Installation of python library 'requests' with command pip3.5
WARNING: You are using pip version 20.1; however, version 20.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Requirement already satisfied: requests>=2.21.0 in /usr/local/lib/python3.5/site-packages (2.24.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.5/site-packages (from requests>=2.21.0) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.5/site-packages (from requests>=2.21.0) (1.25.9)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.5/site-packages (from requests>=2.21.0) (2.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/site-packages (from requests>=2.21.0) (2020.4.5.1)
-- Installation of python library 'protobuf' with command pip3.5
WARNING: You are using pip version 20.1; however, version 20.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Requirement already satisfied: protobuf>=3.11.0 in /usr/local/lib/python3.5/site-packages (3.12.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.5/site-packages (from protobuf>=3.11.0) (46.1.3)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.5/site-packages (from protobuf>=3.11.0) (1.15.0)
-- Installation of python library 'zeroconf' with command pip3.5
WARNING: You are using pip version 20.1; however, version 20.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Requirement already satisfied: zeroconf>=0.25.1 in /usr/local/lib/python3.5/site-packages (0.28.0)
Requirement already satisfied: ifaddr>=0.1.7 in /usr/local/lib/python3.5/site-packages (from zeroconf>=0.25.1) (0.1.7)
-- Installation of python library 'click, bs4 and six' for TTS with command pip3.5
WARNING: You are using pip version 20.1; however, version 20.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Requirement already satisfied: click in /usr/local/lib/python3.5/site-packages (7.1.2)
Requirement already satisfied: bs4 in /usr/local/lib/python3.5/site-packages (0.0.1)
Requirement already satisfied: six in /usr/local/lib/python3.5/site-packages (1.15.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.5/site-packages (from bs4) (4.9.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.5/site-packages (from beautifulsoup4->bs4) (2.0.1)
-- Installation of python library 'tqdm, websocket-client, casttube' for plex/youtube with command pip3.5
WARNING: You are using pip version 20.1; however, version 20.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Requirement already satisfied: tqdm in /usr/local/lib/python3.5/site-packages (4.48.2)
Requirement already satisfied: websocket-client in /usr/local/lib/python3.5/site-packages (0.57.0)
Requirement already satisfied: casttube in /usr/local/lib/python3.5/site-packages (0.2.1)
Requirement already satisfied: six in /usr/local/lib/python3.5/site-packages (from websocket-client) (1.15.0)
Requirement already satisfied: requests in /usr/local/lib/python3.5/site-packages (from casttube) (2.24.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/site-packages (from requests->casttube) (2020.4.5.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.5/site-packages (from requests->casttube) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.5/site-packages (from requests->casttube) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.5/site-packages (from requests->casttube) (1.25.9)
-- Installation of dependencies is done !

**Comment by Licoti** [comment]
J'ai ré-installer jeedom depuis la dernière version buster et depuis plus de problème avec python 3
