### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'cancel'

### ISSUE THREAD

**Issue by vchatela** [guirem/plugin-googlecast#93]
## Description
Scan de device qui prend une erreur : 

## Etapes à reproduire (pour les bugs)

1. Installation sur jeedom v4 depuis market (v2.17 car je n'ai pas trouvé comment installer la v2.18)
2. lancer un scan
```
[2021-11-30 16:07:34][INFO] : ------------------------------------------------------
[2021-11-30 16:07:34][INFO] : ------------------------------------------------------
[2021-11-30 16:07:34][INFO] : GLOBAL------STARTING googlecast
[2021-11-30 16:07:34][INFO] : GLOBAL------Scan Timeout : 5
[2021-11-30 16:07:34][INFO] : GLOBAL------Scan Frequency : 60
[2021-11-30 16:07:34][INFO] : GLOBAL------Log level : debug
[2021-11-30 16:07:34][INFO] : GLOBAL------Socket port : 55012
[2021-11-30 16:07:34][INFO] : GLOBAL------Socket host : 127.0.0.1
[2021-11-30 16:07:34][INFO] : GLOBAL------PID file : /tmp/googlecast.pid
[2021-11-30 16:07:34][INFO] : GLOBAL------Apikey : *******************************
[2021-11-30 16:07:34][INFO] : GLOBAL------TTS Jeedom server : http://10.40.10.40
[2021-11-30 16:07:34][INFO] : GLOBAL------TTS default language : fr-FR
[2021-11-30 16:07:34][INFO] : GLOBAL------TTS default engine : picotts
[2021-11-30 16:07:34][INFO] : GLOBAL------TTS default speech speed : 1.2
[2021-11-30 16:07:34][INFO] : GLOBAL------TTS Google API Key (optional) : NOK
[2021-11-30 16:07:34][INFO] : GLOBAL------TTS default delay before volume restore : 1300 ms
[2021-11-30 16:07:34][INFO] : GLOBAL------TTS default silence before tts : 300 ms
[2021-11-30 16:07:34][INFO] : GLOBAL------Cache status : True
[2021-11-30 16:07:34][INFO] : GLOBAL------Callback : http://127.0.0.1:80/plugins/googlecast/core/php/googlecast.api.php
[2021-11-30 16:07:34][INFO] : GLOBAL------Event cycle : 0.5
[2021-11-30 16:07:34][INFO] : GLOBAL------Main cycle : 2.0
[2021-11-30 16:07:34][INFO] : GLOBAL------Default status message : &nbsp;
[2021-11-30 16:07:34][INFO] : -----------------------------------------------------
[2021-11-30 16:07:34][DEBUG] : Writing PID 17759 to /tmp/googlecast.pid
[2021-11-30 16:07:34][DEBUG] : Init request module v2.25.1
[2021-11-30 16:07:34][INFO] : GLOBAL------Network communication to jeedom OK.
[2021-11-30 16:07:34][DEBUG] : SOCKETHANDLER------Socket interface started
[2021-11-30 16:07:34][DEBUG] : SOCKETHANDLER------LoopNetServer Thread started
[2021-11-30 16:07:34][INFO] : GLOBAL------Socket started and waiting for messages from Jeedom...
[2021-11-30 16:07:34][DEBUG] : WARMUPNOTIF------ Checking file generation...
[2021-11-30 16:07:34][DEBUG] : SOCKETHANDLER------Listening on: [127.0.0.1:55012]
[2021-11-30 16:07:34][DEBUG] : SENDER------Send to jeedom :  {'started': 1, 'source': 'local'}
[2021-11-30 16:07:34][DEBUG] : SCANNER------ Start scanning... (schedule)
[2021-11-30 16:07:34][DEBUG] : ZEROCONF------ Stopping zeroconf monitoring thread...
[2021-11-30 16:07:34][DEBUG] : ZEROCONF------ Start zeroconf monitoring thread...
[2021-11-30 16:07:34][DEBUG] : SOCKETHANDLER------Client connected to [127.0.0.1:48406]
[2021-11-30 16:07:34][DEBUG] : SOCKETHANDLER------Message read from socket: {"apikey": "XXXXXXXXXXXXX", "cmd": "add", "device": {"uuid": "f0256a9b-c7dd-67c6-00dc-66bbbcf2e4b7", "options": {"ignore_CEC": "0"}}}
[2021-11-30 16:07:34][DEBUG] : SOCKETHANDLER------Client disconnected from [127.0.0.1:48406]
[2021-11-30 16:07:35][DEBUG] : SOCKET-READ------Message received in socket JEEDOM_SOCKET_MESSAGE
[2021-11-30 16:07:35][DEBUG] : SOCKET-READ------Received command from jeedom : add
[2021-11-30 16:07:35][DEBUG] : SOCKET-READ------Add device : {'uuid': 'f0256a9b-c7dd-67c6-00dc-66bbbcf2e4b7', 'options': {'ignore_CEC': '0'}}
[2021-11-30 16:07:35][DEBUG] : SCANNER------No connection to device f0256a9b-c7dd-67c6-00dc-66bbbcf2e4b7
[2021-11-30 16:07:35][DEBUG] : SENDER------Send to jeedom :  {'devices': {'f0256a9b-c7dd-67c6-00dc-66bbbcf2e4b7': {'uuid': 'f0256a9b-c7dd-67c6-00dc-66bbbcf2e4b7', 'status': {'uuid': 'f0256a9b-c7dd-67c6-00dc-66bbbcf2e4b7', 'is_stand_by': False, 'is_active_input': False, 'display_name': '', 'status_text': '&nbsp;', 'app_id': '', 'icon_url': '', 'is_busy': False, 'title': '', 'artist': '', 'series_title': '', 'stream_type': '', 'player_state': ''}, 'typemsg': 'info', 'lastOnline': 0, 'online': False, 'lastSent': 1638284855, 'lastOfflineSent': 1638284855, 'options': {'ignore_CEC': '0'}, 'lastScan': 1638284855}}}
[2021-11-30 16:07:38][DEBUG] : SOCKETHANDLER------Client connected to [127.0.0.1:48422]
[2021-11-30 16:07:38][DEBUG] : SOCKETHANDLER------Message read from socket: {"apikey": "XXXXXXXXXXXXX", "cmd": "learnout"}
[2021-11-30 16:07:38][DEBUG] : SOCKETHANDLER------Client disconnected from [127.0.0.1:48422]
[2021-11-30 16:07:38][DEBUG] : SOCKET-READ------Message received in socket JEEDOM_SOCKET_MESSAGE
[2021-11-30 16:07:38][DEBUG] : SOCKET-READ------Received command from jeedom : learnout
[2021-11-30 16:07:38][INFO] : SOCKET-READ------Leave learn mode
[2021-11-30 16:07:38][DEBUG] : SENDER------Send to jeedom :  {'learn_mode': 0, 'source': 'local'}
[2021-11-30 16:07:42][DEBUG] : GLOBAL------Signal 15 caught, exiting...
[2021-11-30 16:07:42][DEBUG] : GLOBAL------Shutdown
[2021-11-30 16:07:42][DEBUG] : GLOBAL------Removing PID file /tmp/googlecast.pid
[2021-11-30 16:07:42][DEBUG] : ZEROCONF------ Stopping zeroconf monitoring thread...
[2021-11-30 16:07:42][ERROR] : ZEROCONF STOP------Exception on netdiscovery : 'bool' object has no attribute 'cancel'
[2021-11-30 16:07:42][DEBUG] : SENDER------Send to jeedom :  {'stopped': 1, 'source': 'local'}
[2021-11-30 16:07:42][DEBUG] : Traceback (most recent call last):
File "/var/www/html/plugins/googlecast/resources/googlecast.py", line 2087, in zeroconfMonitoring_stop
globals.NETDISCOVERY_STOPFN()
File "/var/www/html/plugins/googlecast/resources/pychromecast/pychromecast/__init__.py", line 208, in internal_stop
stop_discovery(browser)
File "/var/www/html/plugins/googlecast/resources/pychromecast/pychromecast/discovery.py", line 135, in stop_discovery
browser.cancel()
AttributeError: 'bool' object has no attribute 'cancel'
[2021-11-30 16:13:02][ERROR] : ZEROCONF STOP------Exception on netdiscovery : 'bool' object has no attribute 'cancel'
```

## Environnement:

* **Version Jeedom**: 4.1.27
* **Plateforme**: linux
* **Version du Plugin**: 2.17

**Comment by vchatela** [comment]
Avec la nouvelle version 2.18 (prise sur la beta)

```
[2021-11-30 16:23:13][INFO] : ------------------------------------------------------
[2021-11-30 16:23:13][INFO] : ------------------------------------------------------
[2021-11-30 16:23:13][INFO] : GLOBAL------STARTING googlecast
[2021-11-30 16:23:13][INFO] : GLOBAL------Scan Timeout : 8
[2021-11-30 16:23:13][INFO] : GLOBAL------Scan Frequency : 60
[2021-11-30 16:23:13][INFO] : GLOBAL------Log level : debug
[2021-11-30 16:23:13][INFO] : GLOBAL------Socket port : 55012
[2021-11-30 16:23:13][INFO] : GLOBAL------Socket host : 127.0.0.1
[2021-11-30 16:23:13][INFO] : GLOBAL------PID file : /tmp/googlecast.pid
[2021-11-30 16:23:13][INFO] : GLOBAL------Apikey : *******************************
[2021-11-30 16:23:13][INFO] : GLOBAL------TTS Jeedom server : http://10.40.10.40
[2021-11-30 16:23:13][INFO] : GLOBAL------TTS default language : fr-FR
[2021-11-30 16:23:13][INFO] : GLOBAL------TTS default engine : jeedomtts
[2021-11-30 16:23:13][INFO] : GLOBAL------TTS default speech speed : 1.2
[2021-11-30 16:23:13][INFO] : GLOBAL------TTS Google API Key (optional) : NOK
[2021-11-30 16:23:13][INFO] : GLOBAL------TTS default delay before volume restore : 1300 ms
[2021-11-30 16:23:13][INFO] : GLOBAL------TTS default silence before tts : 300 ms
[2021-11-30 16:23:13][INFO] : GLOBAL------Cache status : True
[2021-11-30 16:23:13][INFO] : GLOBAL------Callback : http://127.0.0.1:80/plugins/googlecast/core/php/googlecast.api.php
[2021-11-30 16:23:13][INFO] : GLOBAL------Event cycle : 0.5
[2021-11-30 16:23:13][INFO] : GLOBAL------Main cycle : 2.0
[2021-11-30 16:23:13][INFO] : GLOBAL------Default status message : &nbsp;
[2021-11-30 16:23:13][INFO] : -----------------------------------------------------
[2021-11-30 16:23:13][DEBUG] : Writing PID 7511 to /tmp/googlecast.pid
[2021-11-30 16:23:13][DEBUG] : Init request module v2.25.1
[2021-11-30 16:23:13][INFO] : GLOBAL------Network communication to jeedom OK.
[2021-11-30 16:23:13][DEBUG] : SOCKETHANDLER------Socket interface started
[2021-11-30 16:23:13][DEBUG] : SOCKETHANDLER------LoopNetServer Thread started
[2021-11-30 16:23:13][INFO] : GLOBAL------Socket started and waiting for messages from Jeedom...
[2021-11-30 16:23:13][DEBUG] : WARMUPNOTIF------ Checking file generation...
[2021-11-30 16:23:13][DEBUG] : SOCKETHANDLER------Listening on: [127.0.0.1:55012]
[2021-11-30 16:23:13][DEBUG] : SENDER------Send to jeedom :  {'started': 1, 'source': 'local'}
[2021-11-30 16:23:13][ERROR] : GLOBAL------Fatal error : [Errno 105] No buffer space available
[2021-11-30 16:23:13][DEBUG] : Traceback (most recent call last):
File "/var/www/html/plugins/googlecast/resources/googlecast.py", line 2557, in <module>
start(globals.cycle_main)
File "/var/www/html/plugins/googlecast/resources/googlecast.py", line 1918, in start
globals.NETDISCOVERY_CHROMECASTMANAGER = ChromecastBrowserManager()
File "/var/www/html/plugins/googlecast/resources/googlecast.py", line 2077, in __init__
self._zeroconf = zeroconf.Zeroconf()
File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 2494, in __init__
interfaces, unicast, ip_version, apple_p2p=apple_p2p
File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 2328, in create_sockets
respond_socket = add_multicast_member(cast(socket.socket, listen_socket), i, apple_p2p=apple_p2p)
File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 2273, in add_multicast_member
listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available
[2021-11-30 16:23:13][DEBUG] : GLOBAL------Shutdown
[2021-11-30 16:23:13][DEBUG] : GLOBAL------Removing PID file /tmp/googlecast.pid
[2021-11-30 16:23:13][DEBUG] : SENDER------Send to jeedom :  {'stopped': 1, 'source': 'local'}
[2021-11-30 16:23:14][DEBUG] : Exit 0
```

J'ai pourtant redémarré, pas moyen j'ai toujours cette erreur en beta..

**Comment by vchatela** [comment]
En version stable cela ne fonctionne pas, mais en beta j'avais l'erreur `OSError: [Errno 105] No buffer space available`.
 
Je viens de trouver sur le forum home-assistant la solution pour la beta : [ici](https://community.home-assistant.io/t/zeroconf-error/153883/4)

Donc au final pas d'explication pourquoi cela ne fonctionne plus en stable, mais en beta c'est réglé pour moi.
